---
# tasks file for k8s Calico CNI

- name: Show facts available on the system
  ansible.builtin.debug:
    var: ansible_facts
  when: cni_display_facts == "yes"

#################
# Calico specific
#################
# Ensure NetworkManager doesn't manage Calico interfaces
# Reference : https://docs.tigera.io/calico/latest/operations/troubleshoot/troubleshooting#configure-networkmanager
- name: Ensure NetworkManager doesn't interfere with Calico interfaces - Upload {{ centos_calico_netmgr_configfile }}
  template:
    src:   calico.conf.j2
    dest:  "{{ centos_calico_netmgr_configfile }}"
    owner: root
    group: root
    mode:  0640
  notify:
    - restart NetworkManager
  when: (inventory_hostname in groups['k8smasternodes']) and (global_cni == "calico")

# Stop and disable firewalld; use Calico to manage IP filtering on Kubernetes nodes interfaces
# References: https://docs.tigera.io/calico/latest/getting-started/kubernetes/requirements
#             https://docs.tigera.io/calico/latest/network-policy/hosts
- name: Stop and disable firewalld; use Calico to manage IP filtering on Kubernetes nodes interfaces 
  ansible.builtin.service:
    name: firewalld
    state: stopped
    enabled: no
  when: (inventory_hostname in groups['k8smasternodes']) and (global_cni == "calico")

- name: Deploy Calico CNI without Tigera operator on Centos, Redhat or Rocky-Linux 
  become: no
#  #shell: kubectl create -f {{centos_calico_url }} 
#  #command: kubectl --kubeconfig=~{{ remote_user }}/.kube/config create -f {{ centos_calico_url }} 
  command: kubectl create -f {{ centos_calico_url }} 
  when: (inventory_hostname in groups['k8smasternodes']) and (global_cni == "calico")

