- hosts: k8smasternodes 
  remote_user: user1
  become: yes
  become_method: sudo
  become_user: root

  # The following file contains variables to be adjusted to your context or used in several roles
  vars_files:
    - roles/defaults/vars/main.yml 

  roles: 
#  - dependencies
#  - cri-o
#  - k8s
#  - cni
#  - auditing
  - ingress
#  - admission
#  - cisbenchmark

- hosts: k8sworkernodes 
  remote_user: user1
  become: yes
  become_method: sudo
  become_user: root

  # The following file contains variables to be adjusted to your context or used in several roles
  vars_files:
    - roles/defaults/vars/main.yml 

  roles: 
#  - dependencies
#  - cri-o
#  - k8s
#  - cni
#  - cisbenchmark
