- hosts: k8smasternodes 
  remote_user: user1
  become: yes
  become_method: sudo
  become_user: root

  roles: 
  - dependencies
  - cri
#  - k8s
#  - cni
#  - auditing
#  - ingress-kong
#  - ingress-haproxy
#  - ingress-nginx-fabric
#  - mesh-istio
#  - admission
#  - certmanager
#  - neuvector
#  - rancher
#  - gitops
#  - fluentbit
#  - cisbenchmark

- hosts: k8sworkernodes 
  remote_user: user1
  become: yes
  become_method: sudo
  become_user: root

  roles: 
  - dependencies
  - cri
#  - k8s
#  - cni
#  - cisbenchmark
