- hosts: k8smasternodes 
  remote_user: user1
  become: yes
  become_method: sudo
  become_user: root

  roles: 
  - dependencies
  - cri
  - k8s
  - cni
  - auditing
  - ingress-haproxy
#  - ingress-kong
#  - ingress-nginx-fabric
#  - certmanager
#  - rancher
#  - admission
#  - gitops
#  - fluentbit
#  - cisbenchmark

- hosts: k8sworkernodes 
  remote_user: user1
  become: yes
  become_method: sudo
  become_user: root

  roles: 
  - dependencies
  - cri
  - k8s
  - cni
#  - cisbenchmark
