---
# vars file for k8s GitOps component 
#
######################################################
# Common variables
#
# If one wants to display the ansible facts while running the playbook, set the following variable to "yes"
gitops_display_facts: "{{ global_display_facts }}"
centos_gitops: "argocd"
centos_gitops_manifestfile: /tmp/{{ centos_gitops }}_install.yaml
#
# End of common varibles
######################################################
######################################################
# CentOS specific
#
centos_argocd_namespace: "{{centos_gitops}}"
centos_namespace_manifestfile: "/tmp/namespace_gitops.yaml"
centos_argocd_URL: "https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml"
# End of CentOS specific
######################################################

######################################################
# Ubuntu specific
#
#
# End of Ubuntu specific
######################################################
