---
# vars file for k8s HAproxy ingress controller 
#
######################################################
# Common variables
#
# If one wants to display the ansible facts while running the playbook, set the following variable to "yes"
#ingress_haproxy_version: "0.14.4"
ingress_display_facts: "{{ global_display_facts }}"
ingress_haproxy_helmvaluesfile: "/tmp/haproxy-ingress-values.yaml"
#
# End of common varibles
######################################################
######################################################
# CentOS specific
#
centos_ingress: "haproxy"
centos_haproxy_reponame: "haproxy-ingress"
centos_haproxy_helm_repository: "https://haproxy-ingress.github.io/charts"
centos_haproxy_helm_chart: "{{centos_ingress}} {{centos_haproxy_reponame}}/haproxy-ingress"
centos_haproxy_namespace: "haproxy"
# End of CentOS specific
######################################################

######################################################
# Ubuntu specific
#
#
# End of Ubuntu specific
######################################################

