---
# tasks file for gatewayapi-crds

- name: Show facts available on the system
  ansible.builtin.debug:
    var: ansible_facts
  when: ingress_display_facts == "yes"

- name: Deploy Kubernetes Gateway API Custom Resources Definitions (CRD)
  become: no
  shell: |
    kubectl apply -f {{ centos_gwapi_crdurl }}
  when: (inventory_hostname in groups['k8smasternodes']) and (global_install_gwapicrds == "yes")

#- name: Deploy experimental Kubernetes Gateway API Custom Resources Definitions (CRD)
#  become: no
#  shell: |
#    kubectl apply -f {{ centos_gwapi_expcrdurl }}
# when: (inventory_hostname in groups['k8smasternodes']) and (global_install_expgwapicrds == "yes")

