---
# tasks file for cri-o
# Import Linux distribution specific playbooks
- name: Install CRI-O on master Redhat
  import_tasks: rocky-linux.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Install CRI-O on master on Rocky-Linux 
  import_tasks: rocky-linux.yml
  when: ansible_facts['os_family']|lower == 'rocky'
