---
# vars file for k8s NGinx ingress controller 
#
######################################################
# Common variables
#
# If one wants to display the ansible facts while running the playbook, set the following variable to "yes"
#ingress_haproxy_version: "0.14.4"
ingress_display_facts: "{{ global_display_facts }}"
ingress_nginx_helmvaluesfile: "/tmp/nginx-ingress-values.yaml"
#
# End of common varibles
######################################################
######################################################
# CentOS specific
#
centos_ingress: "nginx"
centos_nginx_reponame: "ngf"
centos_nginx_helm_repository: "oci://ghcr.io/nginx/charts/nginx-gateway-fabric"
centos_haproxy_helm_chart: "{{centos_ingress}} {{centos_haproxy_reponame}}/haproxy-ingress"
centos_nginx_namespace: "nginx-gateway"
# End of CentOS specific
######################################################


