---
# vars file for cri-o on Ubuntu/Debian or Rocky-Linux/Centos/Redhat 
#
######################################################
# Common variables
#
# CRI-O version to be installed.
# Ensure this is the same version than the one of Kubernetes
# Available version of Kubernetes and cri-o can be found using :
# curl -s https://packages.cloud.google.com/apt/dists/kubernetes-xenial/main/binary-amd64/Packages | grep Version | awk '{print $2}'
# https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:
k8s_version: "1.27"
crio_version: "{{ k8s_version }}"
crio_minorversion: "1.27.0"
# CRI-O pods subnet
# Ensure chosen subnet doesn't conflict with enterprise subnet that pods should connect to.
crio_pods_subnet: "10.100.0.0/16"
# Allowed OCI images registries
# Add or remove required registries
crio_allowed_registries: "'docker.io', 'registry.fedoraproject.org', 'registry.access.redhat.com'"
# System network configuration file
crio_net_configfile: "/etc/sysctl.d/99-kubernetes-cri.conf"
# Registries configuration file
crio_registries_configfile: "/etc/containers/registries.conf"
# CRI-O configuration file
crio_crio_configfile: "/etc/crio/crio.conf"
# CRI-O bridge configuration file
crio_bridge_configfile: "/etc/cni/net.d/100-crio-bridge.conf"
# Next few lines to be set in case managed machines must access Internet via a proxy
# Example if the proxy requires HTTP Basic authentication
# http_proxy=http://USERNAME:PASSWORD@SERVER:PORT/
#crio_proxy_required: "yes"
crio_proxy_required: "no"
crio_http_proxy:  "http://10.13.4.254:3128"
crio_https_proxy: "http://10.13.4.254:3128"
crio_no_proxy:    ".lab.byte13.org,lab.byte13.org,.cluster.local,cluster.local,localhost,127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
#
# End of common varibles
######################################################
######################################################
# Rocky Linux (CentOS) specific
#
#centos_crio_version: "CentOS_8_Stream"
centos_crio_osversion: "CentOS_8"
#
# CentOS containers libraries repository
# To find proper URL's, check https://cri-o.io/ 
# Read respective .repo file and copy/paste URL's from there
centos_crio_reponame1: "devel:kubic:libcontainers:stable"
centos_crio_repodesc1: "Stable Releases of Upstream github.com/containers packages ({{centos_crio_osversion}})"
centos_crio_repobaseurl1: "https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/{{centos_crio_osversion}}/"
centos_crio_repogpgkey1: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{centos_crio_osversion}}/repodata/repomd.xml.key"
#
# CRI-O repository for CentOS
# To find proper URL's, check https://cri-o.io/ 
# Read respective .repo file and copy/paste URL's from there
#centos_crio_reponame2: "devel:kubic:libcontainers:stable:cri-o:{{crio_version}}"
centos_crio_reponame2: "devel:kubic:libcontainers:stable:cri-o"
centos_crio_repodesc2: "devel:kubic:libcontainers:stable:cri-o:{{crio_version}} ({{centos_crio_osversion}})"
centos_crio_repobaseurl2: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{crio_version}}/{{centos_crio_osversion}}/"
centos_crio_repogpgkey2: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{crio_version}}:/{{centos_crio_osversion}}/repodata/repomd.xml.key"
#centos_crio_pkgname: "cri-o-{{crio_version}}"
centos_crio_pkgname: "cri-o"
centos_criotools_pkgname: "cri-tools"
# Next line to define CRI-O system startup environment file
centos_crio_envfile: "/etc/sysconfig/crio"
# Next line to define CRI-O system startup file
centos_crio_startupfile: "/usr/lib/systemd/system/crio.service"
#
# End of CentOS specific
######################################################

######################################################
# Ubuntu specific
#
ubuntu_crio_version: "xUbuntu_20.04"
# Ubuntu containers libraries repository
ubuntu_crio_repourl1: "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ubuntu_crio_version}}/ /"
ubuntu_crio_gpgkey1: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ubuntu_crio_version}}/Release.key"
ubuntu_crio_repofilename1: "devel:kubic:libcontainers:stable"
# CRI-O repository for Ubuntu
ubuntu_crio_repourl2: "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{crio_version}}/{{ubuntu_crio_version}}/ /"
ubuntu_crio_gpgkey2: "https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:{{crio_version}}/{{ubuntu_crio_version}}/Release.key"
ubuntu_crio_repofilename2: "devel:kubic:libcontainers:stable:cri-o:{{crio_version}}"
#crio_crio_pkgname: "cri-o-{{crio_version}}"
ubuntu_crio_pkgname: "cri-o"
ubuntu_criorunc_pkgname: "cri-o-runc"
ubuntu_criotools_pkgname: "cri-tools"
#
# End of Ubuntu specific
######################################################

