---
# vars file for cri-o Rocky-Linux/Centos/Redhat 
#
######################################################
# Common variables
#
#
# CRI-O version to be installed.
#     Ensure this is the same version than the one of Kubernetes
#     Available version of Kubernetes and cri-o can be found using :
#     curl -s https://packages.cloud.google.com/apt/dists/kubernetes-xenial/main/binary-amd64/Packages | grep Version | awk '{print $2}'
#     https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:
crio_version: "{{ global_k8s_version }}"
crio_minorversion: ""
critools_version: "1.26.0-0"

# CRI-O pods subnet
#     Ensure chosen subnet doesn't conflict with enterprise subnet that pods should connect to.
crio_pods_subnet: "10.100.0.0/16"

# Allowed OCI images registries
#     Add or remove required registries
crio_allowed_registries: "'docker.io', 'registry.fedoraproject.org', 'registry.access.redhat.com'"

# System network configuration file
crio_net_configfile: "/etc/sysctl.d/99-kubernetes-cri.conf"

# Registries configuration file
crio_registries_configfile: "/etc/containers/registries.conf"

# CRI-O configuration file
crio_crio_configfile: "/etc/crio/crio.conf"

# CRI-O bridge configuration file
crio_bridge_configfile: "/etc/cni/net.d/100-crio-bridge.conf"

#
# End of common varibles
######################################################
######################################################
# Rocky Linux (CentOS) specific
#

centos_crio_osversion: "CentOS_8"

# CentOS containers libraries repository
#     To find proper URL's, check https://cri-o.io/ 
#     Read respective .repo file and copy/paste URL's in respective variables below 
centos_crio_reponame1: "devel:kubic:libcontainers:stable"
centos_crio_repodesc1: "Stable Releases of Upstream github.com/containers packages ({{centos_crio_osversion}})"
centos_crio_repobaseurl1: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{centos_crio_osversion}}/"
centos_crio_repogpgkey1: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{centos_crio_osversion}}/repodata/repomd.xml.key"
#
# CRI-O repository for CentOS
# To find proper URL's, check https://cri-o.io/ 
# Read respective .repo file and copy/paste URL's in respective variables below 
centos_crio_reponame2: "devel:kubic:libcontainers:stable:cri-o:{{crio_version}}"
centos_crio_repodesc2: "{{centos_crio_reponame2}} ({{centos_crio_osversion}})"
centos_crio_repobaseurl2: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{crio_version}}/{{centos_crio_osversion}}/"
centos_crio_repogpgkey2: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{crio_version}}/{{centos_crio_osversion}}/repodata/repomd.xml.key"
centos_crio_pkgname: "cri-o"
centos_critools_pkgname: "cri-tools-{{critools_version}}"
# Next line to define CRI-O system startup environment file
centos_crio_envfile: "/etc/sysconfig/crio"
# Next line to define CRI-O system startup file
centos_crio_startupfile: "/usr/lib/systemd/system/crio.service"
#
# End of CentOS specific
######################################################


