---
# tasks file for k8s dependencies

- name: Show facts available on the system
  ansible.builtin.debug:
    var: ansible_facts
  when: global_display_facts == "yes"

# Possibly remove proxy environment variables from /etc/environment 
# To check what programs leverage /etc/environment, run grep -l pam_env /etc/pam.d/* on target host
- name: No proxy required - Remove possible proxy variables from /etc/environment
  ansible.builtin.blockinfile:
    path: /etc/environment
    marker_begin: "# Next lines added by Ansible_Kubernetes-cluster playbook"
    marker_end: "# Previous lines added by Ansible_Kubernetes-cluster playbook"
    block: "" 
  #when: global_proxy_required != "yes" 

# If required, set proxy global environment variables in /etc/environment 
# To check what programs leverage /etc/environment, run grep -l pam_env /etc/pam.d/* on target host
- name: Proxy required - Set proxy global environment variables in /etc/environment
  ansible.builtin.blockinfile:
    path: /etc/environment
    marker_begin: "# Next lines added by Ansible_Kubernetes-cluster playbook"
    marker_end: "# Previous lines added by Ansible_Kubernetes-cluster playbook"
    block: |
      http_proxy="{{ global_http_proxy }}"
      https_proxy="{{ global_https_proxy }}" 
      no_proxy="{{ global_no_proxy }}"
      HTTP_PROXY="{{ global_http_proxy }}"
      HTTPS_PROXY="{{ global_https_proxy }}" 
      NO_PROXY="{{ global_no_proxy }}"
  when: global_proxy_required == "yes" 

# Possibly delete /etc/profile.d/http_proxy.sh
# For programs started in a shell interpreter (typically bash, sh) 
- name: No proxy required - Remove {{ global_proxy_profile }} 
  ansible.builtin.file:
    path: "{{ global_proxy_profile }}" 
    state: absent
  #when: global_proxy_required != "yes" 

# If required, set proxy global environment variables in /etc/profile.d/http_proxy.sh
# For programs started in a shell interpreter (typically bash, sh) 
- name: Proxy required - Set proxy global environment variables in {{ global_proxy_profile }} 
  ansible.builtin.blockinfile:
    path: "{{ global_proxy_profile }}" 
    create: "true"
    marker_begin: "# Next lines added by Ansible_Kubernetes-cluster playbook"
    marker_end: "# Previous lines added by Ansible_Kubernetes-cluster playbook"
    block: |
      export http_proxy="{{ global_http_proxy }}"
      export https_proxy="{{ global_https_proxy }}"
      export no_proxy="{{ global_no_proxy }}"
      export HTTP_PROXY="{{ global_http_proxy }}"
      export HTTPS_PROXY="{{ global_https_proxy }}"
      export NO_PROXY="{{ global_no_proxy }}"
  when: global_proxy_required == "yes" 

# Possibly remove proxy in /etc/dnf/dnf.conf
- name: No proxy required - Remove possible proxy from /etc/dnf/dnf.conf 
  ansible.builtin.blockinfile:
    path: /etc/dnf/dnf.conf 
    backup: yes
    marker_begin: "# Next lines added by Ansible_Kubernetes-cluster playbook"
    marker_end: "# Previous lines added by Ansible_Kubernetes-cluster playbook"
    block: "" 
  #when: global_proxy_required != "yes" 

# If required, set proxy in /etc/dnf/dnf.conf
- name: Proxy required - Set proxy in /etc/dnf/dnf.conf 
  ansible.builtin.blockinfile:
    path: /etc/dnf/dnf.conf 
    backup: yes
    marker_begin: "# Next lines added by Ansible_Kubernetes-cluster playbook"
    marker_end: "# Previous lines added by Ansible_Kubernetes-cluster playbook"
    block: |
      proxy="{{ global_http_proxy }}"
  when: global_proxy_required == "yes" 

# The following repository is required to install Kubernetes using kubeadm
# Must be define early in order to install crictl required by kubeadm and to possibly test CRI 
- name: "Add Kubernetes {{ k8s_version }} Kubernetes yum repository"
  yum_repository:
    name: "{{ global_k8s_reponame1 }}"
    description: "{{ global_k8s_repodesc1 }}"
    baseurl: "{{ global_k8s_repobaseurl1 }}"
    gpgcheck: yes
    gpgkey: "{{ global_k8s_repogpgkey1 }}"

- name: Install possible OS updates using dnf on {{ ansible_facts['os_family'] }}
  dnf:
    name: "*"
    state: latest
    exclude: kubelet
  when: global_upgrade_node == "yes"

- name: Install the latest version of curl
  become: yes
  dnf:
    name: curl
    state: latest
  when: inventory_hostname in groups['k8sworkernodes']

- name: Install the latest version of udica
  become: yes
  dnf:
    name: udica
    state: latest
  when: inventory_hostname in groups['k8sworkernodes']
