---
# tasks file for k8s dependencies

- name: Show facts available on the system
  ansible.builtin.debug:
    var: ansible_facts
  when: dependencies_display_facts == "yes"

- name: Install the latest version of curl
  become: yes
  apt:
    name: curl
    state: latest
  when: inventory_hostname in groups['k8smasternodes']

- name: "Install Helm"
  shell: |
    curl -fsSL -o get_helm.sh dependencies_helm_URL 
    chmod 700 get_helm.sh
    ./get_helm.sh
    rm -f ./get_helm.sh
  when: inventory_hostname in groups['k8smasternodes']
