---
# vars file for ingress-kong 
#
######################################################
# Common variables
#
# If one wants to display the ansible facts while running the playbook, set the following variable to "yes"
ingress_display_facts: "{{ global_display_facts }}"
#
# End of common varibles
######################################################
######################################################
# CentOS specific
#

## Next three lines to install Gateway API CRD's supported by Kong
ingress_gwapicrds_version: "v1.3.0"
centos_kong_gwapi_crdsurl: "https://github.com/kubernetes-sigs/gateway-api/releases/download/{{ingress_gwapicrds_version}}/standard-install.yaml"
#centos_kong_gwapi_expcrdsurl: "https://github.com/kubernetes-sigs/gateway-api/releases/download/{{ingress_gwapicrds_version}}/experimental-install.yaml"

centos_ingress: "kong"
centos_kong_namespace: "kong"
centos_kong_helm_reponame: "kong"
centos_kong_helm_repository: "https://charts.konghq.com"
#centos_kong_helm_chart: "{{centos_kong_helm_reponame}} {{centos_kong_helm_reponame}}/kong"
centos_kong_helm_chart: "{{centos_kong_helm_reponame}} {{centos_kong_helm_reponame}}/ingress" 
ingress_kong_helm_valuesfile: "/tmp/kong-ingress-values.yaml"
# End of CentOS specific
######################################################

